-- §CHAT-SYNC — conversations with the adviser live on the SERVER, not on the device.
--
-- They used to live in `localStorage` under `mt-chats:<user_id>`, which meant a conversation
-- existed only on the machine it was typed on: asking a question on the phone and opening the
-- laptop showed an empty chat rail. The same data was also sitting in plain text on every device
-- the user had ever signed in from, which is why logout has to wipe it (`src/lib/localdata.ts`).
-- Both problems have the same fix — the transcript belongs where the rest of the account lives.
--
-- It lives in the USER'S OWN Durable Object, like every other financial table here: isolation is
-- physical (a separate SQLite database per user), not a `WHERE user_id`. A demo sandbox keeps its
-- chats in its own ephemeral object and loses them with it, which is exactly right.
CREATE TABLE IF NOT EXISTS chats (
  -- Generated by the CLIENT (`c<base36>`), and deliberately so: the rail needs an id the moment
  -- the user clicks "new chat", before any request has been answered. It also makes the one-time
  -- import of the old localStorage conversations idempotent — re-importing the same list from a
  -- second device inserts nothing rather than duplicating every conversation.
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  -- Sort key of the rail. Bumped on every appended message, so the last conversation touched on
  -- ANY device is the one on top everywhere.
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
  -- Also the ordering key: turns are appended, never reordered, and two messages written in the
  -- same second (a question and a fast first answer) must still come back in the order they were
  -- said. A timestamp alone cannot promise that.
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id    TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  role       TEXT NOT NULL,        -- 'user' | 'assistant'
  content    TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_chat ON chat_messages (chat_id, id);
CREATE INDEX IF NOT EXISTS idx_chats_updated ON chats (updated_at DESC);
