// Cloudflare.Env is generated by `wrangler types` from wrangler.jsonc (DB, RECEIPTS,
// ASSETS, APP_TZ). Secrets are added via `wrangler secret put` and declared here.
export interface Env extends Cloudflare.Env {
  MONO_TOKEN: string;
  ANTHROPIC_API_KEY: string;
  WEBHOOK_SECRET: string;
  APP_PASSWORD: string;
  // Telegram-бот (§ROADMAP 1): токен бота, секрет шляху/заголовка вебхука, дозволений chat_id.
  TG_BOT_TOKEN: string;
  TG_SECRET: string;
  TG_CHAT_ID: string;
}
