// Cloudflare.Env is generated by `wrangler types` from wrangler.jsonc (DB, RECEIPTS,
// ASSETS, APP_TZ). Secrets are added via `wrangler secret put` and declared here.
import type { AppDb } from "./lib/platform/db-shim.ts";

// `DB` is narrowed from `D1Database` to `AppDb` — the slice of the D1 API that also works
// against the SQLite inside a user's Durable Object (PLATFORM.md §2). `D1Database` still
// satisfies it, so nothing at the call sites changes; what changes is that reaching for a
// D1-only feature (sessions, `dump()`, `.raw()`) now fails in `tsc` instead of failing in
// production for whichever user happens to hit that endpoint. Check > instruction.
// `SIGNUP` is omitted for a different reason than `DB`: `wrangler types` reads the CURRENT value
// out of `wrangler.jsonc` and emits it as a literal (`SIGNUP: "open"`), because that is what the
// deployment has today. But the whole point of the switch is that flipping it to `"invite"` needs
// no code change — so the code has to accept BOTH values, and inheriting a one-value type would
// make the kill-switch un-flippable without a compile error. Widening it here is the accurate
// statement: the config knows what it is set to, the code knows what it may be set to.
export interface Env extends Omit<Cloudflare.Env, "DB" | "SIGNUP"> {
  DB: AppDb;
  MONO_TOKEN: string;
  ANTHROPIC_API_KEY: string;
  WEBHOOK_SECRET: string;
  APP_PASSWORD: string;
  // Google OAuth (PLATFORM.md §3). These are APPLICATION secrets, not user secrets — they
  // stay global Worker secrets and never move into a user's Durable Object.
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  // Signs session cookies. Separate from APP_PASSWORD so rotating the password does not log
  // everyone out, and so sessions survive the removal of the password gate entirely.
  SESSION_SECRET: string;
  // Encrypts per-user credentials at rest (PLATFORM.md §4). Application secret: the
  // ciphertext lives in each user's Durable Object, the key never leaves the Worker.
  SECRETS_MASTER_KEY: string;
  // Email of the pre-existing single user, seeded into the directory as the owner. Only used
  // by the transitional password login and by the P0.7 data migration.
  OWNER_EMAIL: string;
  /**
   * Who may create an account: `"open"` (default — anyone with a Google account) or `"invite"`
   * (the original whitelist, `POST /api/admin/users/invite`). A plain var rather than a secret,
   * because it is a policy switch and its value is visible from the outside anyway — a stranger
   * finds out by trying to sign in.
   */
  SIGNUP?: "open" | "invite";
  // Dedicated Anthropic key for the public demo (PLATFORM.md §11.3), given its own billing limit
  // on Anthropic's side as the last backstop behind the per-session/global caps. Optional: if
  // unset, demo AI falls back to the regular key (still capped + forced to Haiku).
  DEMO_ANTHROPIC_KEY?: string;
  /**
   * Id of the user this request belongs to. NOT a Cloudflare binding: set by `UserDO.fetch`
   * from the header the Worker attaches after authenticating. Needed because a Durable Object
   * cannot recover its own name (`idFromName` is one-way), yet has to address the user from
   * the outside — e.g. to build this user's monobank webhook URL.
   */
  USER_ID?: string;
  /**
   * Whether this request belongs to the deployment OWNER. NOT a Cloudflare binding: set by
   * `UserDO.appEnv` from the `x-mt-owner` header the Worker attaches after reading the directory.
   *
   * Gates the resources that are the owner's PERSONAL ones even though they look global:
   * the deployment-wide `MONO_TOKEN`/`ANTHROPIC_API_KEY`, and the single `TG_CHAT_ID` the bot
   * pushes to. Anything shared like that must be checked against this flag, or another user's
   * data ends up in the owner's hands (see CLAUDE.md §Безпека).
   */
  IS_OWNER?: boolean;
  /**
   * Internal wiring, NOT a Cloudflare binding: set by `UserDO.fetch` so a handler that
   * rewrites this user's credentials can drop the object's in-memory copy. Optional, because
   * code paths outside the Durable Object (login, OAuth, cron) have no object to notify.
   */
  onSecretsChanged?: () => void;
  /**
   * Internal wiring, NOT a Cloudflare binding: lets the backfill endpoints ask the Durable
   * Object to schedule the next paced step (monobank allows 1 statement request / 60s).
   * The alarm lives on the object; the handler that starts a backfill only knows it wants one.
   */
  scheduleBackfillStep?: (delayMs: number) => void | Promise<void>;
  /**
   * Internal wiring, NOT a Cloudflare binding: "I put work in a queue, re-arm your alarm."
   * Used by §A6 after a job row is inserted — the object owns the single alarm and decides
   * which deadline is nearest; the endpoint only knows it created work.
   */
  scheduleWork?: () => void | Promise<void>;
  // Telegram-бот (§ROADMAP 1): токен бота, секрет шляху/заголовка вебхука, дозволений chat_id.
  TG_BOT_TOKEN: string;
  TG_SECRET: string;
  TG_CHAT_ID: string;
}
